export interface Course {
  name: string;
  duration: string;
  fees: string;
  cutFees?: string;
  internship?: 'Paid' | 'No';
  syllabus?: string[];
}

export const courses: Course[] = [
  {
    name: 'C',
    duration: '1.5 Month',
    fees: '₹ 14,999',
    internship: 'No',
    syllabus: [
      'Basics: Syntax, Variables, Operators',
      'Conditions: if-else, ladders',
      'Loops: while, do-while, for',
      'Functions & Scope',
      'Arrays: 1D, 2D, 3D',
      'Pointers & Memory (malloc, calloc)',
      'Strings & Operations',
      'Structures & Unions',
      'File Handling Basics',
    ],
  },
  {
    name: 'C++',
    duration: '1.5 Month',
    fees: '₹ 14,999',
    internship: 'No',
    syllabus: [
      'Basics & Control Flow',
      'Strings & Functions',
      'Structures & Unions',
      'OOP: Classes & Objects',
      'Constructors & Inheritance',
      'Polymorphism & Encapsulation',
      'File Handling',
      'Advanced C++ & Exception Handling',
      'Templates & STL',
    ],
  },
  {
    name: 'Python',
    duration: '3 Month',
    fees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'Setup & Syntax Basics',
      'Data Types & Structures: List, Dict, Set, Tuple',
      'File Handling & Errors',
      'OOP in Python',
      'Advanced: Decorators, Regex, Lambda',
      'Python for Data: NumPy, Pandas, Matplotlib',
      'ML Tools: SciPy, StatsModels',
    ],
  },
  {
    name: 'Java',
    duration: '4 Month',
    fees: '₹ 34,999',
    internship: 'No',
    syllabus: [
      'Java Basics & OOP',
      'Collections & Exception Handling',
      'Multithreading',
      'Database with JDBC',
      'Spring Basics & REST APIs',
      'JUnit Testing',
      'Enterprise App Development',
    ],
  },
  {
    name: 'Power BI',
    duration: '2 Month',
    fees: '₹ 34,999',
    internship: 'No',
    syllabus: [
      'Intro to BI & Power BI Tools',
      'Data Import: Excel, DBs, etc.',
      'Cleaning & Transforming Data',
      'Modeling & Relationships',
      'DAX Formulas & Measures',
      'Visual Dashboards',
      'Publishing & Sharing Reports',
    ],
  },
  {
    name: 'ETL Library',
    duration: '3 Month',
    fees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'ETL Basics & Data Warehousing',
      'SQL for Extraction & Transformation',
      'Data Processing Techniques',
      'Building ETL Pipelines',
      'Performance Tuning & Projects',
      'Tools: SQL DBs, DBeaver, Airflow',
    ],
  },
  {
    name: 'Adv. Excel',
    duration: '2 Month',
    fees: '₹ 19,999',
    internship: 'No',
    syllabus: [
      'Advanced Formulas & Formatting',
      'Pivot Tables & Charts',
      'VBA & Macros for Automation',
      'Power BI Integration',
      'Business Use Cases',
      'Scenario Analysis & Simulations',
    ],
  },
  {
    name: 'HTML, CSS',
    duration: '3 Month',
    fees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'Web Basics & Structure',
      'HTML Tags & Forms',
      'CSS Styling: Fonts, Colors',
      'Layouts: Flexbox & Grid',
      'Responsive Design',
      'Mini Project: Portfolio Website',
    ],
  },
  {
    name: 'JavaScript',
    duration: '2 Month',
    fees: '₹ 19,999',
    internship: 'No',
    syllabus: [
      'JS Basics: Variables, Loops, DOM',
      'Events & Validations',
      'Arrays, Objects & ES6 Features',
      'Async JS: Promises & Fetch',
      'Local Storage',
      'Mini Project: To-Do App',
    ],
  },
  {
    name: 'Cyprus',
    duration: '2 Month',
    fees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'Getting Started with Cypress',
      'Home',
      'Introduction',
      'Architecture and Environment Setup',
      'Supported Browsers',
      'Test Runner',
      'Build First Test',
      'Fundamental Testing Concepts',
      'Basic Commands',
      'Variables',
      'Aliases',
      'Locators',
      'Assertions',
      'Text Verification',
      'Asynchronous Behavior',
      'Working with XHR',
      'jQuery',
      'Handling Different Web Elements',
      'Checkbox',
      'Tabs',
      'Dropdown',
      'Alerts',
      'Child Windows',
      'Hidden Elements',
      'Frames',
      'Web Tables',
      'Mouse Actions',
      'Advanced Testing Techniques',
      'Cookies',
      'Get and Post',
      'File Upload',
      'Data Driven Testing',
      'Prompt Pop-up Window',
      'Enhancing and Managing Tests',
      'Dashboards',
      'Screenshots and Videos',
      'Debugging',
      'Custom Commands',
      'Fixtures',
      'Environment Variables',
      'Hooks',
      'Configuration, Reporting, and Integration',
      'Configuration of JSON File',
      'Reports',
      'Plugins',
      'GitHub',
    ],
  },
  {
    name: 'Flutter',
    duration: '2 Month',
    fees: '₹ 39,999',
    internship: 'No',
    syllabus: [
      'Flutter & Dart Basics',
      'OOP in Dart',
      'Widgets: Stateless & Stateful',
      'Navigation & Routing',
      'State Management: Provider',
      'API Integration',
      'Firebase Basics',
      'Mini Project: App UI',
    ],
  },
  {
    name: 'MySQL',
    duration: '2 Month',
    fees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'DB Basics & MySQL Tools',
      'Simple SQL Queries',
      'Joins & Table Relations',
      'Data Insert/Update/Delete',
      'Advanced SQL Functions',
      'DB Design & Normalization',
    ],
  },
  {
    name: 'C, C++, Python, Java, HTML, CSS, JavaScript',
    duration: '12 Month (1 Year)',
    fees: '₹ 99,999',
    internship: 'No',
  },
  {
    name: 'AI ML',
    duration: '4 Month',
    fees: '₹ 69,999',
    internship: 'Paid',
    syllabus: [
      'Intro to AI/ML & Applications',
      'Maths & Stats for ML',
      'Python Tools: NumPy, Pandas',
      'EDA & Preprocessing',
      'ML Models: Regression, Trees, SVM',
      'Model Evaluation & Tuning',
      'Clustering & PCA',
      'Advanced ML & Forecasting',
      'Capstone ML Projects',
    ],
  },
  {
    name: 'Gen AI',
    duration: '3 Month',
    fees: '₹ 69,999',
    internship: 'Paid',
    syllabus: [
      'Intro to Generative AI',
      'LLMs & Prompt Writing',
      'Using ChatGPT & AI Tools',
      'Text & Image Generation',
      'Ethical AI Use',
      'Building AI Apps',
      'Final AI Project',
    ],
  },
  {
    name: 'Full Stack/Combo Course',
    duration: '6 Month',
    fees: '₹ 99,999',
    internship: 'No',
    syllabus: [
      'Frontend: HTML, CSS, JavaScript, React',
      'Backend: Node.js, Express, REST APIs',
      'Database: MySQL & MongoDB',
      'Version Control: Git & GitHub',
      'Deployment: Docker, CI/CD',
      'Capstone Project',
    ],
  },
  {
    name: 'Data Analytics',
    duration: '3 Month',
    fees: '₹ 35,000',
    internship: 'No',
    syllabus: [
      'Intro to Data Analytics',
      'Excel for Analytics',
      'SQL for Data Queries',
      'Python Tools for Analysis',
      'Tableau Dashboards',
    ],
  },
  {
    name: 'School Python',
    duration: '2 Month',
    fees: '₹ 14,999',
    cutFees: '₹ 19,999',
    internship: 'No',
    syllabus: [
      'Introduction to Programming Language',
      'Installation',
      'Data Types, Identifier, etc.',
      'Control Flow',
      '  - Sequential',
      '  - if-else',
      '  - if-elif-else',
      '  - if-else ladder',
      'Data Structure',
      '  - String',
      '  - List',
      '  - Tuple',
      '  - Set',
      '  - Dictionary',
      'Function',
      'OOPs',
      'GUI',
    ],
  },
  {
    name: 'School Java',
    duration: '2 Month',
    fees: '₹ 14,999',
    cutFees: '₹ 19,999',
    internship: 'No',
    syllabus: [
      'History, Features, Basic Syntax',
      'Operators',
      'Control Statements',
      '  - Sequential',
      '  - if-else',
      '  - if-else if-else',
      '  - if-else ladder',
      'Functions',
      'OOP',
      'String',
      'Set',
      'HashTable',
      'Array',
      'File Handling',
      'Exception Handling',
      'GUI',
    ],
  },
  {
    name: 'School AI & Web',
    duration: '2 Month',
    fees: '₹ 24,999',
    cutFees: '₹ 29,999',
    internship: 'No',
    syllabus: [
      'Introduction to AI: Understand AI basics and its role in schoolwork and web design.',
      'Frontend Development Basics: Learn website components (HTML, CSS) and AI’s role in web creation.',
      'Building Websites with Lovable: Create simple webpages using Lovable’s AI-powered platform.',
      'AI-Generated Content: Use ChatGPT to write and edit website text.',
      'Designing with Canva AI: Create visuals (e.g., banners) for websites using Canva AI.',
      'Adding Interactivity: Enhance websites with interactive elements like buttons or forms using Lovable and ChatGPT.',
      'AI for Schoolwork: Apply ChatGPT for brainstorming and summarizing school subjects.',
      'Collaboration with AI: Use AI tools (e.g., ChatGPT, Google Docs) for group project planning.',
      'Ethics and AI: Learn responsible AI use, avoiding plagiarism, and understanding limitations.',
      'Final Website Project: Build and present a multi-page website using AI tools.',
      
    ],
  },
];
